site_name: Wiki
theme:
  name: material
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra_css:
  - css/overrides.css

markdown_extensions:
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.snippets

nav:
  - Introduction: index.md
  - Guides:
    - ğŸ§­ Wiki Navigation: guides/wiki_navigation.md
    - ğŸ“ Documentation Notation: guides/documentation_notation.md
  - Modules:
    - ğŸ§© API: 
      - âš™ï¸ Functions: modules/api/functions.md
    - ğŸ§© Core: 
      - TODO: modules/core/index.md
    - ğŸ§© Entity: 
      - TODO: modules/entity/index.md
    - ğŸ§© Math:
      - ğŸŒ€ Data Dimension: modules/math/data_dimension.md
    - ğŸ§© Player:
      - ğŸ‘¤ Player Data: modules/player/player_data.md
      - ğŸ—¡ï¸ Custom Item: modules/player/custom_item.md
      - ğŸ›¡ï¸ Custom Armor: modules/player/custom_armor.md